apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
{{- if .Values.global }}
{{- if .Values.global.WFGlobalSecret }}
{{- range $pkey, $pval := .Values.global.WFGlobalSecret }}
  {{ $pkey }}: {{ $pval }}
{{- end }}
{{- end }}
{{- end }}